# Generated by Django 4.2.5 on 2023-09-08 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicTaskManager', '0003_assignment_classroom_course_major_student_teacher_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
    ]
