# Generated by Django 4.2.5 on 2023-09-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicTaskManager', '0005_alter_teacher_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='major',
            field=models.ManyToManyField(related_name='courseMajor', to='AcademicTaskManager.major'),
        ),
    ]
