# Generated by Django 4.2.5 on 2023-09-08 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicTaskManager', '0007_classroom_semester_course_credithours_course_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('A', models.TextField()),
                ('B', models.TextField()),
                ('C', models.TextField()),
                ('D', models.TextField()),
                ('correctAnswer', models.TextField()),
                ('weight', models.IntegerField(default=1)),
            ],
        ),
        migrations.RenameModel(
            old_name='Submission',
            new_name='AssignmentSubmission',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='correctAnswers',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='dueDate',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='name',
        ),
        migrations.AddField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quizzesCourse', to='AcademicTaskManager.course'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzesClassroom', to='AcademicTaskManager.classroom'),
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='questions',
        ),
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(related_name='quizQuestions', to='AcademicTaskManager.question'),
        ),
    ]
