# Generated by Django 4.2.5 on 2023-09-12 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicTaskManager', '0009_rename_courses_student_registeredcourses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='name',
        ),
        migrations.AddField(
            model_name='classroom',
            name='capacity',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='classroom',
            name='year',
            field=models.IntegerField(default=2023),
        ),
    ]
