# Generated by Django 4.2.5 on 2023-09-12 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicTaskManager', '0010_remove_classroom_name_classroom_capacity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('midtermMarks', models.IntegerField(default=0)),
                ('finalMarks', models.IntegerField(default=0)),
                ('quizzesMarks', models.IntegerField(default=0)),
                ('assignmentsMarks', models.IntegerField(default=0)),
                ('totalMarks', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='dueDate',
        ),
        migrations.AddField(
            model_name='assignment',
            name='marks',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='marks',
            field=models.TextField(default='Not Graded'),
        ),
        migrations.CreateModel(
            name='QuizSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.TextField(default='Not Graded')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizSubmissions', to='AcademicTaskManager.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentQuizSubmissions', to='AcademicTaskManager.student')),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcementsClassroom', to='AcademicTaskManager.classroom')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='gradeBook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courseGradeBook', to='AcademicTaskManager.gradebook'),
        ),
    ]
