# Generated by Django 4.2.5 on 2023-09-12 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicTaskManager', '0011_gradebook_remove_assignment_duedate_assignment_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='graded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='graded',
            field=models.BooleanField(default=False),
        ),
    ]
