# Generated by Django 4.2.5 on 2023-09-13 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicTaskManager', '0012_assignmentsubmission_graded_quizsubmission_graded'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 13, 16, 44, 9, 380287)),
        ),
    ]
