# Generated by Django 4.2.5 on 2023-09-13 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicTaskManager', '0015_assignment_duedate_alter_announcement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 13, 19, 16, 28, 525535)),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='dueDate',
            field=models.DateTimeField(),
        ),
    ]
