# Generated by Django 4.2.5 on 2023-09-14 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicTaskManager', '0016_alter_announcement_date_alter_assignment_duedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 14, 19, 50, 26, 877697)),
        ),
    ]
