# Generated by Django 4.2.5 on 2023-09-14 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicTaskManager', '0018_remove_assignment_submitted_alter_announcement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='marks',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 14, 23, 30, 21, 673382)),
        ),
    ]
