# Generated by Django 4.2.5 on 2023-09-16 23:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicTaskManager', '0019_quiz_marks_alter_announcement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 17, 1, 50, 45, 919891)),
        ),
        migrations.AddField(
            model_name='quiz',
            name='title',
            field=models.CharField(default='kiiw', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 17, 1, 50, 45, 920866)),
        ),
    ]
