# Generated by Django 4.0 on 2023-09-17 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicTaskManager', '0026_rename_user2_chat_student_rename_user1_chat_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 17, 21, 46, 51, 602922)),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 17, 21, 46, 51, 602922)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 17, 21, 46, 51, 602922)),
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
