# Generated by Django 4.0 on 2023-09-17 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicTaskManager', '0029_rename_name_chat_roomname_alter_announcement_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 18, 0, 1, 0, 55485)),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 18, 0, 1, 0, 55485)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 18, 0, 1, 0, 53488)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='marks',
            field=models.IntegerField(default=0),
        ),
    ]
