# Generated by Django 4.0 on 2023-09-19 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicTaskManager', '0031_student_img_teacher_img_alter_announcement_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='course',
            name='gradeBook',
        ),
        migrations.RemoveField(
            model_name='student',
            name='img',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='img',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 19, 22, 46, 11, 879923)),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 19, 22, 46, 11, 879923)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 19, 22, 46, 11, 877929)),
        ),
        migrations.DeleteModel(
            name='GradeBook',
        ),
    ]
