# Generated by Django 4.0 on 2023-09-19 20:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicTaskManager', '0032_remove_course_grade_remove_course_gradebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 19, 22, 46, 37, 172856)),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 19, 22, 46, 37, 173853)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 19, 22, 46, 37, 169866)),
        ),
        migrations.CreateModel(
            name='GradeBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('midtermMark', models.IntegerField(default=0)),
                ('finalMark', models.IntegerField(default=0)),
                ('totalMarks', models.IntegerField(default=0)),
                ('grade', models.CharField(default='In Progress', max_length=10, verbose_name=(('In Progress', 'In Progress'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')))),
                ('assignments', models.ManyToManyField(related_name='assignmentSubmissions', to='AcademicTaskManager.AssignmentSubmission')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseGradeBook', to='AcademicTaskManager.course')),
                ('quizzes', models.ManyToManyField(related_name='quizSubmissions', to='AcademicTaskManager.QuizSubmission')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentGradeBook', to='AcademicTaskManager.student')),
            ],
        ),
    ]
