# Generated by Django 4.0 on 2023-09-19 20:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicTaskManager', '0033_alter_announcement_date_alter_message_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='passedCourses',
        ),
        migrations.AddField(
            model_name='gradebook',
            name='passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 19, 22, 53, 29, 56686)),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 19, 22, 53, 29, 57682)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 19, 22, 53, 29, 53696)),
        ),
    ]
