# Generated by Django 4.0 on 2023-09-19 21:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicTaskManager', '0034_remove_student_passedcourses_gradebook_passed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='submittedBy',
            field=models.ManyToManyField(blank=True, related_name='submittedby', to='AcademicTaskManager.Student'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 19, 23, 23, 15, 509073)),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 19, 23, 23, 15, 509073)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 19, 23, 23, 15, 506088)),
        ),
    ]
