# Generated by Django 4.0 on 2023-09-19 23:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicTaskManager', '0036_alter_announcement_date_alter_message_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradebook',
            name='finalMark',
        ),
        migrations.RemoveField(
            model_name='gradebook',
            name='totalMarks',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 20, 1, 57, 10, 216918)),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 20, 1, 57, 10, 216918)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 20, 1, 57, 10, 213928)),
        ),
    ]
