# Generated by Django 4.0 on 2023-09-19 23:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicTaskManager', '0037_remove_gradebook_finalmark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradebook',
            name='finalMark',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 20, 1, 58, 47, 477404)),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 20, 1, 58, 47, 477404)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 20, 1, 58, 47, 474415)),
        ),
    ]
