# Generated by Django 4.0 on 2023-09-20 00:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicTaskManager', '0038_gradebook_finalmark_alter_announcement_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 20, 2, 4, 7, 730071)),
        ),
        migrations.AlterField(
            model_name='gradebook',
            name='grade',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], default='In Progress', max_length=12),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 20, 2, 4, 7, 730071)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 20, 2, 4, 7, 727081)),
        ),
    ]
