# Generated by Django 4.0 on 2023-09-22 01:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicTaskManager', '0039_alter_announcement_date_alter_gradebook_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='late',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='submissionTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 22, 3, 22, 10, 489498)),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 22, 3, 22, 10, 492488)),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 22, 3, 22, 10, 493508)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 22, 3, 22, 10, 490494)),
        ),
    ]
