# Generated by Django 4.0 on 2023-09-22 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicTaskManager', '0042_alter_announcement_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 22, 17, 36, 6, 529448)),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='submissionTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 22, 17, 36, 6, 526434)),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 22, 17, 36, 6, 529448)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 22, 17, 36, 6, 526434)),
        ),
    ]
