# Generated by Django 4.0 on 2023-09-22 14:37

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicTaskManager', '0043_alter_announcement_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 22, 17, 37, 25, 834496)),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='submissionTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 22, 17, 37, 25, 835477)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 22, 17, 37, 25, 831454)),
        ),
    ]
